create schema FINAL_WORK;

create table PRODUCTS(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(100) NOT NUll,
    PRICE DECIMAL(19, 2) NOT NULL,
    CATEGORY VARCHAR(10) NOT NULL,
    DISCOUNT DECIMAL(19, 2),
    DESCRIPTION VARCHAR(255)
);